title: passionatecoder
author: Ashrin Jose
email: ashrinjose92@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A blog for refreshing your JavaScript basics
theme: minima

# social links
github_username: https://github.com/AshrinJose

show_excerpts: false # set to false to remove excerpts on the homepage
